stages:
  - build
  - test

Refugee.Questionnaire.Build:
  stage: build
  artifacts:
    untracked: false
    when: on_success
    paths:
      - Deployment
    name: "$env:CI_JOB_STAGE_$env:CI_COMMIT_REF_NAME"
    expire_in: 2 day  
  script:
  - 'dotnet publish RQ.Bot/RQ.Bot.csproj -c Release --self-contained -r win-x64 -o Deployment/win64'
  - 'dotnet publish RQ.Bot/RQ.Bot.csproj -c Release --self-contained -r linux-x64 -o Deployment/linux64'
    
Refugee.Questionnaire.CheckQuests:
  stage: test
  script:
    - 'dotnet run --project RQ.ConfigChecker/RQ.ConfigChecker.csproj questions/sample.csv'