---

ansible_host: "{{ vault_ansible_host }}"

questionnaire_bot_instances:
  - port: 9000
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 4
    working_directory: "/opt/questionnaire-bot/instances/9000"
    telegram_token: "{{ vault_questionnaire_bot_9000_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9000_telegram_admin_id }}"
    quest_container_path: "/app/questions/ref-9000.csv"
    enabled: yes
    container_name: "demo_refugee_questionnaire_bot"
  - port: 9100
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 4
    working_directory: "/opt/questionnaire-bot/instances/9100"
    telegram_token: "{{ vault_questionnaire_bot_9100_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9100_telegram_admin_id }}"
    quest_container_path: "/app/questions/vol-9100.csv"
    enabled: yes
    container_name: "demo_volunteers_bot"
